name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag postgres:16va
           docker login --username=${{ vars.USER }} --password=${{ vars.PWD }} ${{ vars.REGISTRY }}
           docker push ${{ vars.REGISTRY }}/flylink/postgres:16va
